// -i- Automatically generated by 'npx turbo @green-stack/core#link:routes', do not modify manually, it will get overwritten

export const routeManifest = {
    ['/']: 'DemoScreen',
    ['/subpages/[slug]']: 'SlugScreen',
    ['/demos/images']: 'ImagesScreen',
    ['/demos/forms']: 'FormsScreen',
} as const

// eslint-disable-next-line @typescript-eslint/ban-types
export type KnownRoutes = keyof typeof routeManifest | (string & {})
